In [10]:
import pandas as pd

In [11]:
# df = pd.read_csv('../Dataset/raw/Oct 1, 2023 - Oct 15, 2023.csv',delimiter=';')

In [12]:
# df

# Lets make a list of the files paths

In [15]:
file_paths =['../Dataset/raw/Oct 1, 2023 - Oct 15, 2023.csv','../Dataset/raw/Oct 15, 2023 - Oct 29, 2023.csv','../Dataset/raw/Oct 29, 2023 - Nov 12, 2023.csv',
             '../Dataset/raw/Nov 12, 2023 - Nov 26, 2023.csv','../Dataset/raw/Nov 26, 2023 - Dec 10, 2023.csv','../Dataset/raw/Dec 10, 2023 - Dec 24, 2023.csv',
             '../Dataset/raw/Dec 24, 2023 - Jan 7, 2024.csv','../Dataset/raw/Jan 7, 2024 - Jan 21, 2024.csv','../Dataset/raw/Jan 21, 2024 - Feb 4, 2024.csv',
             '../Dataset/raw/Feb 4, 2024 - Feb 18, 2024.csv','../Dataset/raw/Feb 18, 2024 - Mar 3, 2024.csv','../Dataset/raw/Mar 3, 2024 - Mar 17, 2024.csv',
             '../Dataset/raw/Mar 17, 2024 - Mar 31, 2024.csv','../Dataset/raw/Mar 31, 2024 - Apr 14, 2024.csv','../Dataset/raw/Apr 14, 2024 - Apr 28, 2024.csv']

In [16]:
print(file_paths)

['../Dataset/raw/Oct 1, 2023 - Oct 15, 2023.csv', '../Dataset/raw/Oct 15, 2023 - Oct 29, 2023.csv', '../Dataset/raw/Oct 29, 2023 - Nov 12, 2023.csv', '../Dataset/raw/Nov 12, 2023 - Nov 26, 2023.csv', '../Dataset/raw/Nov 26, 2023 - Dec 10, 2023.csv', '../Dataset/raw/Dec 10, 2023 - Dec 24, 2023.csv', '../Dataset/raw/Dec 24, 2023 - Jan 7, 2024.csv', '../Dataset/raw/Jan 7, 2024 - Jan 21, 2024.csv', '../Dataset/raw/Jan 21, 2024 - Feb 4, 2024.csv', '../Dataset/raw/Feb 4, 2024 - Feb 18, 2024.csv', '../Dataset/raw/Feb 18, 2024 - Mar 3, 2024.csv', '../Dataset/raw/Mar 3, 2024 - Mar 17, 2024.csv', '../Dataset/raw/Mar 17, 2024 - Mar 31, 2024.csv', '../Dataset/raw/Mar 31, 2024 - Apr 14, 2024.csv', '../Dataset/raw/Apr 14, 2024 - Apr 28, 2024.csv']

In [19]:
dataframes = [pd.read_csv(file,delimiter =';') for file in file_paths]

In [22]:
combined_dataframes = pd.concat(dataframes, ignore_index = True)

In [23]:
combined_dataframes

,Order Item Id,Order Type,Order Flag,Daraz Id,Seller SKU,Daraz SKU,Created at,Updated at,Order Number,Invoice Required,...,Promised shipping time,Premium,Status,Cancel / Return Initiator,Reason,Reason Detail,Editor,Bundle ID,Bundle Discount,Refund Amount
0,206341039307734,Normal,NORMAL,206341039307734,SaraFoods187,127055627_NP-1034460511,2023-10-15 20:59:59,2023-10-18 15:26:47,206341039207734,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,206341039407734,Normal,NORMAL,206341039407734,SaraFoods187,127055627_NP-1034460511,2023-10-15 20:59:59,2023-10-18 15:26:47,206341039207734,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,206445391809042,Normal,NORMAL,206445391809042,SaraFoods037,127052812_NP-1034463348,2023-10-15 20:10:05,2023-10-17 18:23:36,206445391609042,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,206338685057861,Normal,NORMAL,206338685057861,Sara-Sa-263,127043920_NP-1034464123,2023-10-15 19:17:28,2023-10-18 16:08:49,206338684957861,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,206338685157861,Normal,NORMAL,206338685157861,Sara-Sa-263,127043920_NP-1034464123,2023-10-15 19:17:28,2023-10-18 16:08:49,206338684957861,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3553,207979459221129,Normal,NORMAL,207979459221129,SaraFoods209,127055628_NP-1034460512,2024-04-14 11:39:34,2024-04-22 10:27:47,207979459021129,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3554,207979459321129,Normal,NORMAL,207979459321129,SaraFoods209,127055628_NP-1034460512,2024-04-14 11:39:34,2024-04-22 10:27:47,207979459021129,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3555,207976298690386,Normal,NORMAL,207976298690386,SaraFoods068,127055443_NP-1034460493,2024-04-14 11:39:04,2024-04-17 15:17:05,207976298090386,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3556,208117536065601,Normal,NORMAL,208117536065601,SaraFoods068,127055443_NP-1034460493,2024-04-14 10:59:48,2024-04-15 11:13:17,208117535865601,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3557,207981207135022,Normal,NORMAL,207981207135022,SaraFoods018,127052798_NP-1034463335,2024-04-14 08:30:47,2024-04-16 12:22:07,207981207035022,No,...,NaN,No,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# here i have removed the duplicated data from the rows to avoid duplication duirng the combined of diffrenct csv file 

remdup_combined_dataframes =combined_dataframes.drop_duplicates()

In [29]:
remdup_combined_dataframes.shape

(3299, 63)

In [32]:
# After merging and removing duplicate file 
# Lets export new csv file having name Oct 1,2023 - Apr 28, 2024.csv in the preprocessed directory
csv_filename = "../Dataset/preprocessed/Oct 1,2023 - Apr 28, 2024_Merge.csv"
remdup_combined_dataframes.to_csv(csv_filename,index= False,)
print("saved")

saved